### ISSUE TITLE
Crashing when in use

### ISSUE THREAD

**Issue by tgspy** [fireundubh/fo4-mods#1]
When I have the auto loot program turned on in the latest beta, my game freezes up randomly when it's collecting items. Doesn't matter how big the radius is, it still freezes up.

**Comment by fireundubh** [comment]
I've tested with all modules running and was not able to reproduce a freeze. Can you nail down some steps to reproduce your issue? Please also include a list of active modules, affected locations, and whether you upgraded from a previous version.

You could also be experiencing issues related to the use of plugins not made with xEdit. You can use this script to determine which plugins weren't created with xEdit.  Select all of your plugins in xEdit, excluding Fallout4.esm, and run the script. Any plugins that are not version 0.95 could be problematic.

```delphi
unit UserScript;
function Process(e: IInterface): Integer;
begin
	if Signature(e) = 'TES4' then AddMessage(GetElementEditValues(ElementBySignature(e, 'HEDR'), 'Version') + #9 + GetFileName(GetFile(e)));
end;
end.
```

**Comment by tgspy** [comment]
Alright I ran the script and all the plugins I'm running say 0.95. What happens for me, is I either do this:
Load up the holotape, activate bodies and containers module in the part 2 section, set my distance to default, then at any seemingly random time it will crash me. 

I also do:
Turn on all the modules, then activate the two bodies and containers module, then set range to default. and again, random crash

That's about all I can say, it just straight up freezes. If you need me to provide any logs of any sort then I'm happy to oblige

**Comment by tgspy** [comment]
Even running with no plugins installed besides auto loot still gives me crashes

**Comment by fireundubh** [comment]
### General Questions

* What are your hardware specifications?
* Do you have Fallout 4 installed on a SSD?
* Are you running F4SE, ENBoost, or ENBSeries?
* Do you have any other scripted mods installed?
* If you are using an existing save, have you switched out plugins before and thus received the warning about missing objects?

### Auto Loot Questions

* Did you install Auto Loot and then continue an existing save?
* Did you upgrade from an older version of Auto Loot to the current version in an existing save?
* Are you using the latest version of Auto Loot?
* Does the game freeze without Auto Loot installed?
* Does the game freeze with Auto Loot installed but without any modules activated?
* What happens when you start and play a new game as normal with Auto Loot running?
* Where were you in the game world when you've experienced freezes?

**Comment by tgspy** [comment]
i5 4690
R9 280 3GB
8gb's of ram
Installed on a HDD

I'm running enboost/enb

Other scripted mods include better item sorting, key nuker, and crafting workbenches

Yes I have, I switch out mods all the time after I've finished testing them

I did install auto loot on an existing save 

I didn't upgrade to a new version

I use the newest version

No the game doesn't freeze without auto loot installed

That's the thing, if I only enable the bodies and containers option, it still picks stuff up, and I still experience crashes, whether or not I have any modules selected or none

I'll try out a new save

I would be walking around and it would simple crash

**Comment by tgspy** [comment]
Trying it with a new game seems to work flawlessly, however, even after reinstalling on my current game, I still get freezes.

**Comment by fireundubh** [comment]
> Trying it with a new game seems to work flawlessly, however, even after reinstalling on my current game, I still get freezes.

Then the freezing issue you've described isn't caused by the mod and is instead localized to that save.

Switching plugins in and out of existing saves has always been a source of frustration, so much so to the point where someone had to create a program that allowed you to clean up the mess that created for Skyrim saves.

There's also the possibility that the blame rests with recent updates to the game. Saves are supposed to be forward-compatible, but perhaps you've stumbled onto an issue that betrays that ideal.

**Comment by tgspy** [comment]
Any chances of fixing this in a current game or is the only option at the moment to start a new game?

**Comment by fireundubh** [comment]
For you, you have to start a new game. The problem rests specifically with your existing save.
