### ISSUE TITLE
lockups caused by autoloot

### ISSUE THREAD

**Issue by phuhque** [fireundubh/fo4-mods#10]
I have noticed for some reason, when I have auto loot enabled my system will lockup rather often.  If I disable and and fully remove autoloot, this does not occur at all.  I have attempted to reduce the radiator range and it seems to have a correlation.  If at 1024 or less, it is fairly stable, but at 2048 it is a crap shoot.

Usually, the screen will freeze, but the audio will continue. Active working set memory can remain the same or drop to just over 700 megs, with peak around 2 gb.  Is there a debug or logging function in conjunction with this?  

This is one of my favorite mods as I can never find the bodies in the grass.except at night with a scrap tags active.

**Comment by fireundubh** [comment]
I hate to say this, but your issue probably isn't related to the mod.

Auto Loot just generates a list of object references in a space around the player and calls `Activate()` on each reference to pick them up. The more likely culprit is either the game or another mod, including improperly installed retextures, that affects one or more of those references.

It is possible though that Auto Loot is simply taxing the resources your system made available to the game or which the game has available. That would account for the increased stability you've experienced at lower radii.

**Comment by phuhque** [comment]
I started a new game.  Got 7 hours into it and the lockups began.  At first it was just once or so every couple of hours, then every hour.  I had to disable it completely finally because as soon as the game would start and I enabled the features, it would hard lock.  One thing I noticed is that sometimes, the memory usage at time of lockup was around 700mb.

**Comment by fireundubh** [comment]
I don't know what to tell you. I've been working on new features all day today and yesterday, and the game hasn't locked up once for me. Turn on the Papyrus log and see if anything's flooding the engine. Sounds like there's a memory leak _somewhere_, but memory leaks aren't exactly something I can fix with Papyrus.

**Comment by phuhque** [comment]
Interesting tidbit...  I started getting flooded with these before a crash:
[03/19/2016 - 01:46:55PM] warning: Property ReconScopeQuest on script ReconScopeScript attached to Active effect 1 on  (00195D78) cannot be initialized because the script no longer contains that property
[03/19/2016 - 01:46:56PM] warning: Property reconMarkedEnemy on script ReconScopeScript attached to Active effect 2 on  (00195D78) cannot be initialized because the script no longer contains that property
[03/19/2016 - 01:46:56PM] warning: Property ReconScopeQuest on script ReconScopeScript attached to Active effect 2 on  (00195D78) cannot be initialized because the script no longer contains that property.

The odd thing is that they have a hard coded drive letter as part of their own script;
	[None].ReconScopeScript.OnEffectStart() - "g:\_F4\Art\Raw\ScriptsMilestone\ReconScopeScript.psc" Line 11

I am going to switch from the recon sight to something else, see if that helps.

**Comment by phuhque** [comment]
So, i had a drive letter labeled G.  I changed that.  I got fewer crashes.  I just had another one, and this is what was at the end of the logs:

[03/19/2016 - 04:30:52PM] warning: Assigning None to a non-object variable named "::temp1"
stack:
	[Active effect 9 on  (00000014)].dubhAutoLootEffect.OnEffectStart() - "D:\Projects\Assets\FO4 Scripts\scripts\source\dubhAutoLootEffect.psc" Line 60
[03/19/2016 - 04:30:53PM] error: Unable to call Activate - no native object bound to the script object, or object is of incorrect type
stack:
	[Item 343 in container  (00000014)].ObjectReference.Activate() - "<native>" Line ?
	[Active effect 9 on  (00000014)].dubhAutoLootEffect.OnEffectStart() - "D:\Projects\Assets\FO4 Scripts\scripts\source\dubhAutoLootEffect.psc" Line 60
[03/19/2016 - 04:30:53PM] warning: Assigning None to a non-object variable named "::temp1"
stack:
	[Active effect 9 on  (00000014)].dubhAutoLootEffect.OnEffectStart() - "D:\Projects\Assets\FO4 Scripts\scripts\source\dubhAutoLootEffect.psc" Line 60

There are a number of these entries.  A note:  They start with Item 169 and progress to 343.  Is there a chance that as your process progresses I have a variable that is looped back over?  All the instances are for the same container, 00000014.  At least in this log.

**Comment by fireundubh** [comment]
> I started getting flooded with these before a crash

The warnings you're getting related to `ReconScopeScript` just mean that there's a filled property in the plugin that isn't used in the script. Not a big deal, but this is a Bethesda bug unless you have a mod overriding that script.

> All the instances are for the same container, 00000014.

`00000014` is the player.

`dubhAutoLootEffect` is the effect script for auto loot modules that are not Bodies, Containers, or Flora.

> [03/19/2016 - 04:30:53PM] error: Unable to call Activate - no native object bound to the script object, or object is of incorrect type

The object the script was trying to auto loot is no longer there.

> `[Item 343 in container (00000014)].ObjectReference.Activate() - "" Line ?`

This indicates the script was trying to auto loot an item in the player's inventory, which says that by the time the script looped over that reference, you had already picked up the item. But this does not make sense because this script will try to activate objects only when `objLoot.GetContainer() == None`. I'll add an additional check for `objLoot.GetContainer() != Game.GetPlayer()`, but I don't know if that will even do anything.

That said, I don't think these errors are causing or exacerbating a memory leak.

I did make a change in the next version that empties the loot array when the loop finishes and when the module is deactivated. Again, I don't know if this will do anything. Arrays should not persist in the way that I'm thinking, but if they do for some reason, then there would be a memory leak. Clearing the loot array periodically doesn't hurt, so why not.

**Comment by fireundubh** [comment]
Please deactivate all modules, uninstall the mod, and install the latest version.

Create a new issue if you experience further lockups.
