### ISSUE TITLE
some items not picked up

### ISSUE THREAD

**Issue by DrWolfnstine** [fireundubh/fo4-mods#12]
hey just wanted to let you know that sometimes loose items will not be picked up, items off all types seem to be affected, even those of the same type that it did pick up in the very same room.

**Comment by fireundubh** [comment]
That is a known issue attributed to a bug in the game. I will investigate further after the Creation Kit is released. SmkViper (Bethesda's programmer who is responsible for Papyrus) is not allowed to talk to modders about mod-related issues until then.

**Comment by DrWolfnstine** [comment]
ahh ok, figgured it was probably noticed, if it helps I think it might have something to do with a locked container being nearby. Perhaps it tries to loot the locked container and since it can't it produces and erorr and stops picking thing up in that cell?

**Comment by fireundubh** [comment]
Auto Loot gathers up a list of references (objects) within some distance of the player, and then iterates through that list, checking each reference against a number of criteria, and when a reference matches the criteria, the reference is activated (i.e., the item is looted.)

That criteria includes the question: "is this container locked?" If the answer is yes, then Auto Loot skips all of the logic for activating that reference, so I don't see how skipping the auto loot logic would produce an error.

I actually think that this issue is more likely the result of Auto Loot working faster than the game can keep up, and because the game can't keep up, it's throwing out instructions and skipping over references. However, there's nothing in the log about the game dumping stacks, so I'd need SmkViper to investigate and confirm as that would be an engine issue that is totally not resolvable by any modder.

The best that I could do would be to slow down Auto Loot to work at some arbitrary interval, as we do with Skyrim mods. I don't want to do that if that's not the problem though, and I'm not even sure I _can_ do that with this version of Papyrus.

**Comment by DrWolfnstine** [comment]
Interesting, this is actually the first chance I have to gotten to see how the mods I use actually work so I am enjoying learning as I go. The Skyrim version of auto-loot was already perfected when I started using it, and the Fallout NV version wasn't perfect but no one was working on it at the time for me to ask questions. Seeing as they did use their old standby engine for F4 I would not be surprised if was the cause and I hope you can match the speeds when the creation kit comes out. I am such a huge pack rat in F4 I HAVE to pick up everything, so I will probably wait on my completionist play-through till they release the kit.

**Comment by fireundubh** [comment]
This issue is now resolved. Please update to the latest version.

**Comment by DrWolfnstine** [comment]
Awesome! Thanks!
