### ISSUE TITLE
auto loot problem

### ISSUE THREAD

**Issue by prayoga-masagi** [fireundubh/fo4-mods#13]
i using this mod a week ago, don't have trouble in first 24 hours,
after that, this mod make fallout 4 crashing when loot something 
( i don't know what kind item who make it crash ),
so i update this mod about yesterday, it still crash if auto loot to player inventory,
after i move auto loot to settlement, the crash is gone, but it bring new problem
some time, after load area(after loading) the "auto steal"(auto pick owned item) is active 
(but in the auto loot config / option writes auto steal do not active)
and yes, every body attack my player because he steal something 
please fix this , sorry for my bad English

**Comment by fireundubh** [comment]
> after that, this mod make fallout 4 crashing when loot something 

If you have Automatron installed, you will experience more crashes with or without mods.

Some crashes are due to the use of UI mods that have not been updated to support Automatron. You should completely uninstall any UI mods, including deleting the `interface` folder in your `Fallout 4\Data` directory.

All crashes are unrelated to Auto Loot.

> some time, after load area(after loading) the "auto steal"(auto pick owned item) is active 

There are two ways to activate Auto Steal:

* Use the toggle in the Advanced Setup.
* Type the following command in the in-game console: `set dubhAutoLootStolenFilter to 0`

Those are the only two ways to activate Auto Steal. There is no other way to activate Auto Steal.

If there is a bug in the game that is causing global variables to reset to zero, I can do nothing about that.

However, if you believe that Auto Steal has been activated in error:

1. Using the in-game console, type `sglv` to show all global variables.
2. If the value of `dubhAutoLootStolenFilter` is `0`, then Auto Steal was activated.
3. To disable Auto Steal, type `set dubhAutoLootStolenFilter to 1` or toggle the setting in the Advanced Setup menu.

**Comment by prayoga-masagi** [comment]
thanks for quick respond.
yes i am using automatron dlc
maybe i just need to deactivate automatron until next patch is come,
anyway, what software do you use for make this mod, it seem more advance than fo4edit
i like to try make player control by companion ai(travel and combat),
and using VANS as travel destination. 
once again, thanks for your reply, 
and sorry for unrelated question

**Comment by Tellerd** [comment]
I am having a crashing issue, as well, and it began prior to installing Automatron.  I have set the range of auto looting very low to avoid overloading my system.  Still, the game locks up from time to time while auto loot is active.  I have a theory....

I THINK this may be happening when I approach a body that contains a legendary item.  With auto loot off, we get the screen that pops up when looting, showing the legendary item (ta-da!) and asking you to accept it.  I believe this is somehow crashing auto loot.  Perhaps auto loot is trying to accept it too quickly for my system?

**Comment by piyason** [comment]
set inventory to settlement is slove crash problem as well
but i think if we can filter what item that should send to settlement like junk or misc item will be really good

love this mod so far

**Comment by prayoga-masagi** [comment]
i don't know its bug or not,
1. in dead body all of item is taken by auto loot, but equipped weapon not
2. sometime the auto loot, loot very fast, especially after entering a room , but some time i don't know auto loot work or not, because raider still wearing his armor after 2 minutes he/she died

**Comment by fireundubh** [comment]
@Tellerd:

> I am having a crashing issue, as well, and it began prior to installing Automatron. 

There is no way for Auto Loot to cause crashes. It just isn't possible. I'm sorry that you're experiencing crashes, but Auto Loot doesn't do anything hacky or exotic to work. Auto Loot uses bog standard functions used elsewhere by Bethesda. It's more likely that you installed another mod without all of its assets. Missing meshes or textures, and outdated UI mods, will crash the game, for example.

@prayoga-masagi:

> what software do you use for make this mod, it seem more advance than fo4edit

[FO4Edit](https://github.com/TES5Edit/TES5Edit) for the plugin, and Orvid's [Caprica](https://github.com/Orvid/Caprica) for compiling the scripts.

> i think if we can filter what item that should send to settlement like junk or misc item will be really good

I thought about it, but unfortunately, this is too much work.

Creating terminal menus is a pain. To show feedback when you select a menu item, you have to create two terminal menu items for every item. I had to create 60 menu items to show 30 settlements, and I had to break those 60 menu items across 4 pages because the terminal menu lags when there are too many items per page. To allow you to direct specific item categories to specific settlements, I'd have to create 540 more menu items to cover the 9 modules, or 544 menu items total, including the player as a destination. No thanks.

If we had a better menu system like SkyUI for configuring mods while in the game, I'd do it, but the terminal design is just terrible.

> in dead body all of item is taken by auto loot, but equipped weapon not

* If Filter Mode is enabled, only items that have a module will be auto looted. There are no modules for armor and weapons.
* If Filter Mode is disabled and the Bodies module is active, all items should be auto looted from bodies.

> some time i don't know auto loot work or not, because raider still wearing his armor after 2 minutes he/she died

If there are a lot of bodies and/or you have a lot of modules active, it will take time to iterate through the loot array.

**Comment by phuhque** [comment]
I have seen the same crashing with AutoLoot running.  However, I do not believe it is directly related to the mod itself.  With FO4 up and running will all of my mods (with and without Autoloot) I have noticed a steady climb in memory usage.  This tells me there is a memory leak that isn't being recovered.  After a couple of hours (with the help of Autoloot) I will routinely experience a CTD.  

This did not happen before, I just got freezes.  Now however, i can still enjoy my game with Autoloot quietly sending my gains to Sanctuary.  I have also not had the Auto Steal mysteriously turn on since my first encounter with it.

Now the only suggestion I have is that there are many quest items that are set to auto trigger when you touch an item that end up getting broken because the mod works so well.  I am trying to get one of my quests with a holotape re-kickstarted.  Shouldn't be to hard.  

I did encounter one NPC body type that Autoloot doesn't work on.  Triggerman from Good neighbor.  When you have to clear out the warehouses, you have a good number of bodies.  Not a big deal, just an observation for the sake of completion.

**Comment by fireundubh** [comment]
> Now the only suggestion I have is that there are many quest items that are set to auto trigger when you touch an item that end up getting broken because the mod works so well.

You can drop items that have a script attached to them, turn off Auto Loot, and then pick them up manually.

Or you can just remove those items from the formlists in the plugin. There aren't too many.

**Valuables:**

- `BottleCapMinePlacedCaps "Caps" [ACTI:002472ED]`
- `loot_capsStash_tin "Caps Stash" [ACTI:0003000C]`
- `MoneyShotPlacedCaps "Caps" [ACTI:0020ABE3]`
- `MS11GuidanceChip "NX-42 Guidance Chip" [MISC:0004E3A2]`

**Junk 1:**

- `BobbyPinBox "Bobby Pin Box" [MISC:0008FCA8]`

**Junk 2:**

- `PlayerHouse_Lamp01Off "Pre-War Lamp" [MISC:00078309]`
- `PowerRelayCoil "Power Relay Coil" [MISC:00091FDE]`
- `VaultSuitPackage01 "Vault 111 Jumpsuit" [MISC:0008C1AE]`
- `VaultSuitPackage114 "Vault 114 Jumpsuit" [MISC:00195385]`

> I am trying to get one of my quests with a holotape re-kickstarted.

There are no holotapes in the formlists, so if you auto looted any holotapes, they were on a body or in a container.

Filter Mode exists so that you can control which items are auto looted from bodies and containers.

> I did encounter one NPC body type that Autoloot doesn't work on. Triggerman from Good neighbor. When you have to clear out the warehouses, you have a good number of bodies.

I wouldn't know why. Triggermen use the Human race which has the ActorTypeHuman keyword, so Auto Loot should loot those bodies. There are no fixes to be made that I can make. Fallout 4 has bugs. That's all I can say.

**Comment by prayoga-masagi** [comment]
fireundubh thanks again for reply, 
i have a question, i know making terminal menu is annoying, 
but, can you type the console command (with explain) 
i like to loot ammo to player and anything else to sanctuary

**Comment by piyason** [comment]
fireundubh i am thank you very much for reply and everything

**Comment by fireundubh** [comment]
> i have a question, i know making terminal menu is annoying, 
> but, can you type the console command (with explain) 
> i like to loot ammo to player and anything else to sanctuary

I realized that I didn't need to add hundreds of menu items, so I implemented a solution in the latest update.

You can now:

1. Choose a settlement as the default container in Container Setup.
2. Then, override the default container with the player for any module in Container Setup>Preferences.

Please redownload and reinstall the mod, overwriting all files.

`dubhAutoLootEffectScript.pex` is no longer needed as well because none of the modules share a script anymore.

I'm closing this thread. Please create a new issue if you have any other feedback.
