### ISSUE TITLE
"Expanded Buildable Area" conflicts with SpringCleaning

### ISSUE THREAD

**Issue by clampi** [fireundubh/fo4-mods#6]
Version used: Latest version (150%), SpringCleaning 2.05

Description/how to reproduce:
Use 2 mods, load order can only be F4.esm->SpringCleaning.esm->Expanded Buildable Area [ammount].esp
1) Start a new game, go through chargen and exit v111
2) Arrive in Sanctuary, go through Codswort mini-quest until is told to visit the other town.
3) Kill any hostiles in the area (radroaches), secure the Sanctuary workshop
4) Observe that Expanded Buildable Area works by going in workshop mode beyond the green-margin.
5) Observe that there are thing that can't be scrapped right around the workshop, like leaves, dead grass, debris and decals.
6) Save and exit F4.
7) disable the Expanded Buildable Area mod, start F4 again and load save made at step (6).
8) Observe that thing that should be scrappable are now as such in workshop mode.

Further Info:
There isn't any obvious conflict between the 2 mods in F4Edit, so the conflict is somewhere in how the Fallot4 engine works. It would be nice if it will be documented in the description page. It would be nicer if the root cause can be found such that the information soaks-up into the Fallout4 modder community and a possible workaround is devised.

**Comment by fireundubh** [comment]
I use [Pro Landscaping Kit](https://github.com/fireundubh/fo4-mods/tree/master/Pro%20Landscaping%20Kit), instead of Spring Cleaning, and I experience the same issue. Reloading a save in the area that should contain scrappable objects (e.g., Red Rocket) _sometimes_ allows those objects to be scrappable. I don't know if anything can be done to solve this problem, as this looks like an engine issue.
